sudo: required

language: node_js

node_js:
  - 16

cache:
  directories:
  - node_modules

before_install:
  - npm install -g codecov

script:
  - npm test -- --coverage --forceExit
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
